### ISSUE TITLE
Fix node name for TS parser

### ISSUE THREAD

**Issue by ArnaudBarre** [sxzz/ast-explorer#102]
### Describe the bug

Thank you so much for this tool!

Because TS have some markers on SyntaxKind like FirstStatement and LastStatement to allow people to check if a syntax kind is a statement by checking if the value is in that range, doing `SyntaxKind[node.kind]` will give the marker name for node that are a boundary.

This is because all boundaries are [at the end of the enum](https://github.com/microsoft/TypeScript/blob/main/tests/baselines/reference/api/typescript.d.ts#L4037-L4067) 

I worked around in a project by keeping only the first value like this:
```ts
const syntaxKinds = {} as Record<SyntaxKind, string>;
for (const [key, value] of Object.entries(SyntaxKind)) {
  if (typeof value === "number" && !syntaxKinds[value]) {
    syntaxKinds[value] = key;
  }
}
```
Then replace `SyntaxKind[node.kind]` by `syntaxKinds[node.kind]`

I think adding this to [this file])(https://github.com/sxzz/ast-explorer/blob/298b7e09dd1a407b2c0cb7ca891ee960dd59fb21/composables/parser/javascript/typescript.ts#L35) should do the trick?

### Reproduction

https://ast.sxzz.moe/#eNo9yLEKgCAQBuBXOf65oTWj12hyOUTEkFPUghDfvZtav4EEg4sfbq7G0rGgKPS3+B+cgsvSOjEdtO5KWWlYIbJILOHm4E9fW8xiYWjbrEzMD0YPHQ8=

### System Info

```Shell
Chrome
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment]
Thanks for your code!
