### ISSUE TITLE
Page HTML/htmlparser2 have memery leak

### ISSUE THREAD

**Issue by Gehbt** [sxzz/ast-explorer#107]
### Describe the bug

At the page, click left editor. prefeormance monitor
![image](https://github.com/user-attachments/assets/09cdcc0d-ce7d-4f53-999e-04fc721c16a8)

Clone the repo, console log
![image](https://github.com/user-attachments/assets/ebf1ea1c-397e-49ab-a3d0-8393ced17474)

### Reproduction

none

### System Info

```Shell
Browsers:
    Edge: Chromium (131.0.2903.70), ChromiumDev (130.0.2821.1)
    Internet Explorer: 11.0.22621.3527
```

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment]
Fixed via 33f1296029dfb1cac4f99c532cbc07f9e62c20e6
