### ISSUE TITLE
Add oxc parser

### ISSUE THREAD

**Issue by 0xdevalias** [sxzz/ast-explorer#26]
### Clear and concise description of the problem

As a developer using `ast-explorer`, I want to be able to see the AST's parsed by `oxc`

### Suggested solution

Mostly opening this as a tracking issue since I noticed your comment on the `oxc` repo RE: wasm:

> I'd like to add Oxc parser to my [AST Explorer](https://ast.sxzz.moe/)
> 
> _Originally posted by @sxzz in https://github.com/oxc-project/oxc/issues/301#issuecomment-1754520023_

---

> I noticed that the playground's `package.json` loads it as such:
> 
> - https://github.com/oxc-project/oxc/blob/main/website/package.json#L32C5-L32C19
>   - `"@oxc/wasm-web": "link:../npm/wasm-web",`
> 
> Yet there doesn't seem to be a `npm/wasm-web` in the main repo?
> 
> - https://github.com/oxc-project/oxc/tree/main/npm
> 
> **Edit:** Actually, I see now, it's the `package.json` has scripts to build it:
> 
> - https://github.com/oxc-project/oxc/blob/main/website/package.json#L8-L10
>   - `"wasm-dev": "wasm-pack build --out-dir ../../npm/wasm-web --target web --dev --scope oxc ../crates/oxc_wasm",`
>   - `"wasm-build": "wasm-pack build --out-dir ../../npm/wasm-web --target web --release --scope oxc ../crates/oxc_wasm"`
> - https://github.com/oxc-project/oxc/tree/main/crates/oxc_wasm
> 
> _Originally posted by @0xdevalias in https://github.com/oxc-project/oxc/issues/301#issuecomment-1835439409_

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sxzz** [comment]
Oxc parser is supported via 9c4e4ad4c526f62e112be3b4471644b60de309a9. Thanks to https://github.com/oxc-project/oxc/issues/301.
