### ISSUE TITLE
add code/node highlighting based on selected code/node

### ISSUE THREAD

**Issue by 0xdevalias** [sxzz/ast-explorer#33]
### Clear and concise description of the problem

On https://astexplorer.net/ it's possible to see/highlight the corresponding node when code is selected, and code when the node is selected. This makes it really easy to check that we're looking at the part of the AST/code that we expect we are.

![image](https://github.com/sxzz/ast-explorer/assets/753891/110f823a-2f98-4905-a4f5-0e7284c3b4e6)

### Suggested solution

It would be awesome if this ast-explorer supported a feature like this, as it has far more modern versions of the AST parsers.

### Alternative

Living without highlighting, or using the older versions of the parsers on https://astexplorer.net/

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sxzz** [comment]
This feature is supported. Please ensure `Hide location data` is disabled.

**Comment by 0xdevalias** [comment]
Oh, sweet! I somehow missed that. Thanks :)
