### ISSUE TITLE
Wrong compiler name for oxc

### ISSUE THREAD

**Issue by Boshen** [sxzz/ast-explorer#39]
### Describe the bug

https://github.com/sxzz/ast-explorer/blob/9c4e4ad4c526f62e112be3b4471644b60de309a9/composables/language/javascript.ts#L136

;-)

### Reproduction

None

### System Info

```Shell
None
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment]
Sorry for copying directly! Fixed
