### ISSUE TITLE
Get updates for OXC parser

### ISSUE THREAD

**Issue by ArnaudBarre** [sxzz/ast-explorer#48]
### Clear and concise description of the problem

Most parsers seems very up to date expect OXC. I currently working on making the OXC AST more compatible with  ESTree and would love to use this to quickly compare the differences

### Suggested solution

Track with dependabot?

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by ArnaudBarre** [comment]
My bad, this just that the wasm package is not updated as often as the napi parser!

**Comment by sxzz** [comment]
Most parsers are imported from CDN (jsdelivr), which is always the latest.
