### ISSUE TITLE
In dark mode, the Option label style is wrong

### ISSUE THREAD

**Issue by chansee97** [sxzz/ast-explorer#70]
### Describe the bug

![image](https://github.com/sxzz/ast-explorer/assets/90271994/299bff01-f931-4e58-9028-bea5582de41a)
It should be a black background.

### Reproduction

none

### System Info

```Shell
none
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment]
It works on macOS. 🤔
